name = "slm-libwebsockets"
version = "0.0.0"

[dependencies]

[dependencies.libwebsockets]
pkg="libwebsockets"
version="4.3.3"
type="conan"
options.shared="False"
options.avoid_sigpipe_ign="False"
options.disable_logs="False"
options.enable_access_log="False"
options.enable_acme="False"
options.enable_builtin_getifaddrs="True"
options.enable_builtin_sha1="True"
options.enable_cgi="False"
options.enable_custom_headers="True"
options.enable_daemonize="False"
options.enable_deprecated_lws_dll="False"
options.enable_detailed_latency="False"
options.enable_dir="False"
options.enable_diskcache="False"
options.enable_extensions="False"
options.enable_external_http_proxying="True"
options.enable_external_poll="False"
options.enable_fallback_gethostbyname="False"
options.enable_file_ops="True"
options.enable_fts="False"
options.enable_gcov="False"
options.enable_gencrypto="False"
options.enable_generic_sessions="False"
options.enable_http2="True"
options.enable_http_basic_auth="True"
options.enable_http_brotli="False"
options.enable_http_proxy="False"
options.enable_http_stream_compression="False"
options.enable_http_uncommon_headers="True"
options.enable_ipv6="False"
options.enable_jose="False"
options.enable_lejp="True"
options.enable_lejp_conf="False"
options.enable_lws_dsh="False"
options.enable_lwsac="True"
options.enable_lwsws="False"
options.enable_network="True"
options.enable_peer_limits="False"
options.enable_plugins="False"
options.enable_ranges="False"
options.enable_secure_streams="False"
options.enable_secure_streams_proxy_api="False"
options.enable_secure_streams_static_policy_only="False"
options.enable_secure_streams_sys_auth_api_amazon_com="False"
options.enable_selftests="False"
options.enable_sequencer="True"
options.enable_server_status="False"
options.enable_socks5="False"
options.enable_spawn="False"
options.enable_stats="False"
options.enable_struct_json="False"
options.enable_struct_sqlite3="False"
options.enable_sys_async_dns="False"
options.enable_sys_dhcp_client="False"
options.enable_sys_ntpclient="False"
options.enable_threadpool="False"
options.enable_udp="True"
options.enable_unix_sock="True"
options.enable_zip_fops="False"
options.logs_timestamp="True"
options.role_dbus="False"
options.role_h1="True"
options.role_mqtt="False"
options.role_raw_file="True"
options.role_raw_proxy="False"
options.role_ws="True"
options.ssl_client_use_os_ca_certs="True"
options.ssl_server_with_ecdh_cert="False"
options.with_hubbub="False"
options.with_libevent="False"
options.with_libmount="False"
options.with_libuv="False"
options.with_netlink="False"
options.with_sqlite3="False"
options.with_ssl="openssl"
options.with_zlib="False"
options.without_client="False"
options.without_server="False"
options.linux.fPIC="True"
options.macos.fPIC="True"

[dependencies.openssl]
pkg="openssl"
version="3.2.2"
type="conan"
options.shared = "False"
options.386 = "False"
options.enable_trace = "False"
options.enable_weak_ssl_ciphers = "False"
options.no_apps = "False"
options.no_aria = "False"
options.no_asm = "False"
options.no_async = "False"
options.no_autoload_config = "False"
options.no_bf = "False"
options.no_blake2 = "False"
options.no_camellia = "False"
options.no_cast = "False"
options.no_chacha = "False"
options.no_cms = "False"
options.no_comp = "False"
options.no_ct = "False"
options.no_deprecated = "False"
options.no_des = "False"
options.no_dgram = "False"
options.no_dh = "False"
options.no_dsa = "False"
options.no_dso = "False"
options.no_ec = "False"
options.no_ecdh = "False"
options.no_ecdsa = "False"
options.no_engine = "False"
options.no_filenames = "False"
options.no_fips = "False"
options.no_gost = "False"
options.no_idea = "False"
options.no_legacy = "False"
options.no_md2 = "True"
options.no_md4 = "False"
options.no_mdc2 = "False"
options.no_module = "False"
options.no_ocsp = "False"
options.no_pinshared = "False"
options.no_rc2 = "False"
options.no_rc4 = "False"
options.no_rc5 = "False"
options.no_rfc3779 = "False"
options.no_rmd160 = "False"
options.no_seed = "False"
options.no_sm2 = "False"
options.no_sm3 = "False"
options.no_sm4 = "False"
options.no_sock = "False"
options.no_srp = "False"
options.no_srtp = "False"
options.no_sse2 = "False"
options.no_ssl = "False"
options.no_ssl3 = "False"
options.no_stdio = "False"
options.no_threads = "False"
options.no_tls1 = "False"
options.no_ts = "False"
options.no_whirlpool = "False"
options.no_zlib = "False"
options.linux.fPIC = "True"
options.macos.fPIC = "True"
options.windows.capieng_dialog = "False"
options.windows.enable_capieng = "False"
